{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0a994e3c-4bb4-4196-840d-3c78c182596e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os,sys, json,re, pickle\n",
    "import magic, hashlib,  traceback ,ntpath, collections ,lief\n",
    "from capstone import *\n",
    "from capstone.x86 import *\n",
    "import torch.nn as nn\n",
    "import lief,traceback\n",
    "from elftools.elf.elffile import ELFFile\n",
    "from transformers import AdamW,AutoTokenizer\n",
    "from tqdm import tqdm  # for our progress bar\n",
    "from sklearn.metrics import precision_recall_fscore_support , accuracy_score,f1_score, confusion_matrix,mean_squared_error, mean_absolute_error, r2_score\n",
    "from numpy import *\n",
    "from num2words import num2words\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f654b05f-145b-405f-b917-6bd69545e2ac",
   "metadata": {},
   "outputs": [],
   "source": [
    "# BIN_FILE_TYPE = 'PE' #or ELF\n",
    "# # bin_path = '/home/raisul/DATA/temp/x86_pe_msvc_O2_static/'\n",
    "# # # bin_files = [os.path.join(bin_path, f) for f in os.listdir(bin_path) if f.endswith(\".exe\")]\n",
    "# # bin_files = [os.path.join(bin_path, f) for f in os.listdir(bin_path) if f.endswith(\".exe\")]\n",
    "# bin_path = '/home/raisul/DATA/x86_pe_msvc_O2_static/' #/home/raisul/DATA/temp/x86_pe_msvc_O2_static/'\n",
    "# bin_files = [f for f in os.listdir(bin_path) ]\n",
    "# bin_files       = [ os.path.join(os.path.join(bin_path, f),f+'.exe' )  for f in bin_files]\n",
    "# ground_truth_path ='/home/raisul/ANALYSED_DATA/ghidra_x86_pe_msvc_O2_static/'  \n",
    "\n",
    "# MAX_SEQUENCE_LENGTH = 10\n",
    "\n",
    "\n",
    "\n",
    "BIN_FILE_TYPE = 'ELF' #or ELF\n",
    "# bin_path = '/home/raisul/DATA/temp/x86_pe_msvc_O2_static/'\n",
    "# # bin_files = [os.path.join(bin_path, f) for f in os.listdir(bin_path) if f.endswith(\".exe\")]\n",
    "# bin_files = [os.path.join(bin_path, f) for f in os.listdir(bin_path) if f.endswith(\".exe\")]\n",
    "bin_path = '/home/raisul/DATA/x86_O2_d4/' #/home/raisul/DATA/temp/x86_pe_msvc_O2_static/'\n",
    "bin_files = [f for f in os.listdir(bin_path) ]\n",
    "# bin_files       = [ os.path.join(os.path.join(bin_path, f),f+'.exe' )  for f in bin_files]\n",
    "ground_truth_path ='/home/raisul/ANALYSED_DATA/ghidra_x86_O2_d4/'  \n",
    "meta_path = '/home/raisul/pun_dataset/meta/' \n",
    "save_path = \"/home/raisul/ANALYSED_DATA/jump_data/\"\n",
    "MAX_SEQUENCE_LENGTH = 10\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "335baa66-5a95-41fe-9539-afaca9c882dd",
   "metadata": {},
   "outputs": [],
   "source": [
    "bin_files = bin_files#[0:10000]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "570e85a9-7759-492b-b1ec-59444c0605e8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8d01dfce-edb1-4a0a-a0a8-fbaf3fac12cc",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "def get_ground_truth_ghidra(exe_path, text_section_offset , text_section_len):\n",
    "\n",
    "    text_sextion_end = text_section_offset + text_section_len\n",
    "    \n",
    "    elf_file_name = os.path.basename(exe_path)\n",
    "    ghidra_file_path = os.path.join(ground_truth_path, elf_file_name.split('.')[0]) + '.json'\n",
    "    \n",
    "    with open(ghidra_file_path, \"r\") as file:\n",
    "        ghidra_data = json.load(file)\n",
    "\n",
    "    ground_truth_offsets = list(ghidra_data.keys())\n",
    "\n",
    "    ground_truth_offsets = [int(i) for i in ground_truth_offsets]\n",
    "    ground_truth_offsets = [x for x in ground_truth_offsets if text_section_offset <= x <= text_sextion_end]\n",
    "    ground_truth_offsets.sort()\n",
    "    return ground_truth_offsets\n",
    "\n",
    "import re\n",
    "def find_switch_lines(filepath):\n",
    "    try:\n",
    "        with open(filepath, \"r\" , encoding=\"utf-8\", errors=\"replace\") as f:   \n",
    "            lines = f.readlines()\n",
    "\n",
    "        # Remove block comments across the file\n",
    "        code = ''.join(lines)\n",
    "        code = re.sub(r'/\\*.*?\\*/', '', code, flags=re.DOTALL)\n",
    "        lines = code.splitlines()\n",
    "\n",
    "        switch_lines = []\n",
    "        for idx, line in enumerate(lines, start=1):\n",
    "            line_clean = re.sub(r'//.*', '', line)  # remove inline comments\n",
    "            if re.search(r'\\bswitch\\s*\\(.*?\\)', line_clean):\n",
    "                switch_lines.append(idx)\n",
    "\n",
    "        return switch_lines\n",
    "\n",
    "    except FileNotFoundError:\n",
    "        print(f\"File not found: {filepath}\")\n",
    "        return []\n",
    "\n",
    "def print_c_code(filepath):\n",
    "    return\n",
    "    if not os.path.exists(filepath):\n",
    "        print(f\"❌ File not found: {filepath}\")\n",
    "        return\n",
    "\n",
    "    print(f\"📄 Printing contents of: {filepath}\\n\" + \"-\"*60)\n",
    "\n",
    "    with open(filepath, \"r\") as f:\n",
    "        for i, line in enumerate(f, start=1):\n",
    "            print(f\"{i:4d}: {line.rstrip()}\")\n",
    "\n",
    "\n",
    "\n",
    "import shutil\n",
    "from datetime import datetime\n",
    "def copy_files_to_new_dir(src1, src2, src3, new_dir_path):\n",
    "    # return\n",
    "    os.makedirs(new_dir_path, exist_ok=True)\n",
    "    # Copy both files into the new directory\n",
    "    for src in [src1, src2,src3]:\n",
    "        shutil.copy(src, new_dir_path)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "def is_jump_table_candidate(insn):\n",
    "    if insn.mnemonic != \"jmp\":\n",
    "        return False\n",
    "    \n",
    "    if len(insn.operands) != 1:\n",
    "        return False\n",
    "    \n",
    "    op = insn.operands[0]\n",
    "    if op.type == CS_OP_MEM:\n",
    "        mem = op.mem\n",
    "        if mem.scale in (4, 8) and mem.index != 0:\n",
    "            return 1\n",
    "    if op.type == CS_OP_REG:\n",
    "        # We may still need to check prior instruction patterns (e.g., LEA/MOV)\n",
    "        return 2\n",
    "    return False\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "1c2f8ec7-72bd-4fd8-aef3-90ef4e0fcaa1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T17051FDE8DF3D009BF5BF062C415EC88E805C957316956AF67C8C96A0EB6019E94FE468.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T187213BCA1287E2355FB7A4931761AE00DF52C418A8FAFB55BC6C0318255397051FBADC.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T1ADF049A69A0CC714207F406E891D6ACEC17DC4B25C518AB37C2FA606206068B0E7E25E.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 18, in <module>\n",
      "    elffile = ELFFile(f)\n",
      "              ^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 84, in __init__\n",
      "    self._identify_file()\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 570, in _identify_file\n",
      "    elf_assert(magic == b'\\x7fELF', 'Magic number does not match')\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 80, in elf_assert\n",
      "    _assert_with_exception(cond, msg, ELFError)\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 143, in _assert_with_exception\n",
      "    raise exception_type(msg)\n",
      "elftools.common.exceptions.ELFError: Magic number does not match\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T16A21AA8124DB7062A29346771FC78D00701ED2B321CCEA6EFC7D54BABF805CA61B15B4.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T147F0DAC518AA8BA16AB3A8B95B0A5804306A980361DDBC2AFD1D21D24F010274ED4E9B.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 18, in <module>\n",
      "    elffile = ELFFile(f)\n",
      "              ^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 84, in __init__\n",
      "    self._identify_file()\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 570, in _identify_file\n",
      "    elf_assert(magic == b'\\x7fELF', 'Magic number does not match')\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 80, in elf_assert\n",
      "    _assert_with_exception(cond, msg, ELFError)\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 143, in _assert_with_exception\n",
      "    raise exception_type(msg)\n",
      "elftools.common.exceptions.ELFError: Magic number does not match\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 18, in <module>\n",
      "    elffile = ELFFile(f)\n",
      "              ^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 84, in __init__\n",
      "    self._identify_file()\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 570, in _identify_file\n",
      "    elf_assert(magic == b'\\x7fELF', 'Magic number does not match')\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 80, in elf_assert\n",
      "    _assert_with_exception(cond, msg, ELFError)\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 143, in _assert_with_exception\n",
      "    raise exception_type(msg)\n",
      "elftools.common.exceptions.ELFError: Magic number does not match\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 31, in <module>\n",
      "    ground_truth_offsets = get_ground_truth_ghidra(bin_file_path, text_section_offset , len(textSection))\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/tmp/ipykernel_430200/3715514896.py\", line 8, in get_ground_truth_ghidra\n",
      "    with open(ghidra_file_path, \"r\") as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/ANALYSED_DATA/ghidra_x86_O2_d4/T17201A2ED29F75581F037B629069A646A3138D4932CC8BF64BD2E01138F06DAC477D791.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 18, in <module>\n",
      "    elffile = ELFFile(f)\n",
      "              ^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 84, in __init__\n",
      "    self._identify_file()\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 570, in _identify_file\n",
      "    elf_assert(magic == b'\\x7fELF', 'Magic number does not match')\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 80, in elf_assert\n",
      "    _assert_with_exception(cond, msg, ELFError)\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 143, in _assert_with_exception\n",
      "    raise exception_type(msg)\n",
      "elftools.common.exceptions.ELFError: Magic number does not match\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T131F02B1CCB7AB5E7AB7F5234475B881690CA621006A82D3641C51CD4E0580DA3DFB786.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T1F5F0595848AE4741F8D359EECFD74820351EEBC332A87A34FE0D21834F1A088667A18A.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T1BA71DB080FBD62D64627DE26B68B5356D11B000A12367AA6F28CD1704F5DC28F2EDEE9.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 18, in <module>\n",
      "    elffile = ELFFile(f)\n",
      "              ^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 84, in __init__\n",
      "    self._identify_file()\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 570, in _identify_file\n",
      "    elf_assert(magic == b'\\x7fELF', 'Magic number does not match')\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 80, in elf_assert\n",
      "    _assert_with_exception(cond, msg, ELFError)\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 143, in _assert_with_exception\n",
      "    raise exception_type(msg)\n",
      "elftools.common.exceptions.ELFError: Magic number does not match\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T1A2E02B085C93BEC1E88F442E979A0F1537B9D843208CB920FC0E016D1F23560A8E5ABA.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T1E22115C0F1BD5561B3E30178BB45AC00A20ACC683FBC7C59FD5C40749B092C359D9595.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T1FC119C0654E916F4217B24390FC73601535CEAB76298F11CFC5EA2D64F82F2282F5B0C.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T17CD0A98148ED9C012E2A468C3C1BC27A260748A3422AD301F02A83DB1280AE0E8A2EC2.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T158F0DC8A21802489A73781391FA14300F529C89B3AE83000FE0F8C720F7242722F3FE1.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T170214CA51D7A82A993BBC4C4047AF843D78D681311DA6D31FC9C38175B53493A28C399.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T1EDE0728498CF69D038A300A8CE971820229EAF0360ACF4B1FC0C115A8F00611C4B6E0A.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T1730175B1B70DD2415C37150B8A2DA406838CC0317DE06E3AE81B7BB05EA094B32FBF05.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T1CAF0C28828FB49F0675B107A5B8E9845361BC84750CCFD247F0D4281AF444609EAABAF.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T13E21898369B44911B6F3413D879B5B45256DC11722E13B10AD6E31807FF2A47E1F2BCE.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T199214888C8EA11B2065307AC929BC401E15ACC1BF18EB949F82D629A7F4F66560F9FC5.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T19DE048917A4A7E99947280C9874D40C0D929941320B5B5B4F81C557F3F75C0695A5EEC.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T170F0E21839EB02E54D46C03C7B0A517465A56E03198EDC1CBFDDD1E09FC7976A5F2346.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 31, in <module>\n",
      "    ground_truth_offsets = get_ground_truth_ghidra(bin_file_path, text_section_offset , len(textSection))\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/tmp/ipykernel_430200/3715514896.py\", line 8, in get_ground_truth_ghidra\n",
      "    with open(ghidra_file_path, \"r\") as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/ANALYSED_DATA/ghidra_x86_O2_d4/T1C411881E18A1826170E3D2798BCB441D7128A983229CB4C5FF0F65A23FC0034AAF97E3.json'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\n",
      "/home/raisul/DATA/x86_O2_d4/T1E7741AB1DB5D10667537427DD716840A961EC2E773B0EC72ACADE2887E900DF80BCD5A /media/raisul/nahid_personal/clones_100k/zsaegesser_____CS511/promela/pan.c\n",
      "\n",
      "\n",
      "\n",
      "0xa8b7  :  jmp rax\n",
      "Last 20 instructions:\n",
      "0xa86f movsxd rcx, dword ptr [rdi + rcx*4]\n",
      "0xa873 add rcx, rdi\n",
      "0xa876 notrack jmp rcx\n",
      "0xa880 movsxd rsi, esi\n",
      "0xa883 add edx, 1\n",
      "0xa886 mov byte ptr [rax], dl\n",
      "0xa888 mov byte ptr [rax + rsi*2 + 2], r14b\n",
      "0xa88d mov byte ptr [rax + rsi*2 + 3], r13b\n",
      "0xa892 cmp r12d, 2\n",
      "0xa896 je 0xa8c0\n",
      "0xa898 mov rax, qword ptr [rip + 0xf8c1]\n",
      "0xa89f lea rdi, [rip + 0x797a]\n",
      "0xa8a6 jg 0xa8af\n",
      "0xa8a8 lea rdi, [rip + 0x7999]\n",
      "0xa8af pop rbx\n",
      "0xa8b0 pop rbp\n",
      "0xa8b1 pop r12\n",
      "0xa8b3 pop r13\n",
      "0xa8b5 pop r14\n",
      "0xa8b7 jmp rax\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 18, in <module>\n",
      "    elffile = ELFFile(f)\n",
      "              ^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 84, in __init__\n",
      "    self._identify_file()\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 570, in _identify_file\n",
      "    elf_assert(magic == b'\\x7fELF', 'Magic number does not match')\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 80, in elf_assert\n",
      "    _assert_with_exception(cond, msg, ELFError)\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 143, in _assert_with_exception\n",
      "    raise exception_type(msg)\n",
      "elftools.common.exceptions.ELFError: Magic number does not match\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T17E213BCF959E7074B5B3D016CF826D9F1277E89AB3B0BDFA902D0286512A9A7081D05A.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 31, in <module>\n",
      "    ground_truth_offsets = get_ground_truth_ghidra(bin_file_path, text_section_offset , len(textSection))\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/tmp/ipykernel_430200/3715514896.py\", line 8, in get_ground_truth_ghidra\n",
      "    with open(ghidra_file_path, \"r\") as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/ANALYSED_DATA/ghidra_x86_O2_d4/T17D11C27FC62EC392D87305A7431781261A0A743027E17D3BA11F25D0B90009A32AFFD7.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 18, in <module>\n",
      "    elffile = ELFFile(f)\n",
      "              ^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 84, in __init__\n",
      "    self._identify_file()\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 570, in _identify_file\n",
      "    elf_assert(magic == b'\\x7fELF', 'Magic number does not match')\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 80, in elf_assert\n",
      "    _assert_with_exception(cond, msg, ELFError)\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 143, in _assert_with_exception\n",
      "    raise exception_type(msg)\n",
      "elftools.common.exceptions.ELFError: Magic number does not match\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 18, in <module>\n",
      "    elffile = ELFFile(f)\n",
      "              ^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 84, in __init__\n",
      "    self._identify_file()\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/elf/elffile.py\", line 570, in _identify_file\n",
      "    elf_assert(magic == b'\\x7fELF', 'Magic number does not match')\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 80, in elf_assert\n",
      "    _assert_with_exception(cond, msg, ELFError)\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/elftools/common/utils.py\", line 143, in _assert_with_exception\n",
      "    raise exception_type(msg)\n",
      "elftools.common.exceptions.ELFError: Magic number does not match\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T19BD0A7908AFF5DC55927819A9E9AC475170EDCD729CCE561F16DC8814F404C9D0CF3E4.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T1F8F0AC50F44712E12F7BC049D919C532CA819E92608D60FEF45E131327B6C37001977E.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T19D516325C451549B71FAE1F77F821E8E345F592E91C398A299E700BC0CFCCA582B0ED2.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_430200/1833799726.py\", line 36, in <module>\n",
      "    with open(meta_file_path, \"r\") as f:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/raisul/anaconda3/envs/pytorch/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 324, in _modified_open\n",
      "    return io_open(file, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/raisul/pun_dataset/meta/T15D019965C7886211B6239173DF618D0C512EFD20BAE87BB7C21F4022A5A10D861F1BE5.json'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\n",
      "/home/raisul/DATA/x86_O2_d4/T1B9844288247FA0A517A3D722825B4EA10658D007F2D4AD60F59FB6BC0FC6414E7FF7A6 /media/raisul/nahid_personal/clones_100k/harmim_____vut-dip/benchmarks/scalability/benchmarks-subset/libgpg-error-1.21_build_tests_t-lock.c\n",
      "\n",
      "\n",
      "\n",
      "0x4437  :  jmp rax\n",
      "Last 20 instructions:\n",
      "0x43d4 mov qword ptr [rcx], rax\n",
      "0x43d7 xor eax, eax\n",
      "0x43d9 mov qword ptr [rdi + 8], 0\n",
      "0x43e1 mov qword ptr [rdi + 0x10], 0\n",
      "0x43e9 mov qword ptr [rdi + 0x20], 0\n",
      "0x43f1 ret \n",
      "0x43f8 sub rsp, 8\n",
      "0x43fc call 0x2460\n",
      "0x4401 mov dword ptr [rax], 0x16\n",
      "0x4407 mov eax, 0xffffffff\n",
      "0x440c add rsp, 8\n",
      "0x4410 ret \n",
      "0x4420 endbr64 \n",
      "0x4424 test rdi, rdi\n",
      "0x4427 je 0x4448\n",
      "0x4429 mov rax, qword ptr [rip + 0x12cf0]\n",
      "0x4430 test rax, rax\n",
      "0x4433 je 0x4440\n",
      "0x4435 xor esi, esi\n",
      "0x4437 jmp rax\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "\n",
    "\n",
    "SEQUENCES = []\n",
    "LABELS     = []\n",
    "HISTORY_SIZE =20\n",
    "for bin_file_name in bin_files:\n",
    "\n",
    "    bin_file_path = os.path.join(bin_path , bin_file_name)\n",
    "    md = Cs(CS_ARCH_X86, CS_MODE_64)\n",
    "    md.detail = True\n",
    "    offset_inst = {}\n",
    "\n",
    "    ground_truth_offsets = None\n",
    "\n",
    "\n",
    "    try:\n",
    "        with open(bin_file_path, 'rb') as f:\n",
    "        \n",
    "            if BIN_FILE_TYPE == \"ELF\":\n",
    "                elffile = ELFFile(f)\n",
    "                textSection = elffile.get_section_by_name('.text').data()\n",
    "                text_section_offset = elffile.get_section_by_name('.text')['sh_offset']\n",
    "                \n",
    "              \n",
    "            elif BIN_FILE_TYPE == \"PE\":\n",
    "    \n",
    "                        \n",
    "                pe_file = lief.parse(bin_file_path)\n",
    "                text_section = pe_file.get_section(\".text\")\n",
    "                text_section_offset = text_section.pointerto_raw_data\n",
    "                textSection = bytes(text_section.content)\n",
    "                \n",
    "            ground_truth_offsets = get_ground_truth_ghidra(bin_file_path, text_section_offset , len(textSection))\n",
    "            \n",
    "        meta_file_path = os.path.join(meta_path , bin_file_name+'.json')\n",
    "\n",
    "        # Open and load the JSON\n",
    "        with open(meta_file_path, \"r\") as f:\n",
    "            meta_data = json.load(f)\n",
    "        src_file_path = meta_data ['x86_O2_d4']['src_path']\n",
    "        #hack bad\n",
    "\n",
    "        if 'nahid_personal' not in src_file_path:\n",
    "            src_file_path = src_file_path.replace('/media/raisul/' , '/media/raisul/nahid_personal/')\n",
    "\n",
    "        \n",
    "        inst_sizes = {}\n",
    "        instruction_history = []  # Circular buffer for last 20 instructions\n",
    "        for byte_index in ground_truth_offsets:\n",
    "     \n",
    "                instruction = next(md.disasm(textSection[byte_index-text_section_offset: byte_index+15-text_section_offset ],   byte_index ), None)\n",
    "\n",
    "                if instruction is None:\n",
    "                    continue\n",
    "                if len(instruction_history) >= HISTORY_SIZE:\n",
    "                    instruction_history.pop(0)\n",
    "                instruction_history.append(instruction)\n",
    "\n",
    "                # if is_jump_table_candidate(instruction):\n",
    "                if instruction.mnemonic=='jmp' and instruction.op_str=='rax':\n",
    "                    switch_src_lines =  find_switch_lines(src_file_path) \n",
    "                    if len(switch_src_lines)>0:\n",
    "\n",
    "                        #\n",
    "                        if instruction_history[-2].group(CS_GRP_JUMP):          #instruction_history[-2].mnemonic in ['je' , 'jz']:\n",
    "                            continue\n",
    "                        ghidra_file_path = os.path.join(ground_truth_path, bin_file_name) + '.json'\n",
    "                        copy_files_to_new_dir(src_file_path,bin_file_path ,ghidra_file_path, os.path.join(save_path , os.path.basename(src_file_path.split('.')[0])+bin_file_name ) )\n",
    "                        \n",
    "                        \n",
    "                        \n",
    "                        \n",
    "                        \n",
    "                        \n",
    "                        print_c_code(src_file_path)                    \n",
    "                        print(\"\\n\\n\")\n",
    "                        print(bin_file_path ,src_file_path)\n",
    "                        print(\"\\n\\n\")\n",
    "                        \n",
    "                        print(hex(byte_index) ,' : ' , instruction.mnemonic+ ' ' + instruction.op_str)\n",
    "                        print(\"Last 20 instructions:\")\n",
    "                        for  hist_inst in instruction_history:\n",
    "                            print(hex(hist_inst.address) , hist_inst.mnemonic, hist_inst.op_str)\n",
    "                        print(\"\\n\\n\\n\\n\\n\")\n",
    "                        break\n",
    "            \n",
    "    except Exception as e:\n",
    "        traceback.print_exc()\n",
    "        continue                \n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "18822c3e-1051-4af1-a406-675a2f226be9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "25c17257-46c0-47e1-8906-11b9ecfe0be6",
   "metadata": {},
   "outputs": [],
   "source": [
    "#jupyter nbconvert --to script data_pipe.ipynb\n",
    "# accelerate launch data_pipe.py > log.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "77604d7b-3ef5-4029-9044-db47877067e2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3d902dcc-0da1-46a1-a0ee-8905bd3ad4a1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pytorch",
   "language": "python",
   "name": "pytorch"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
